// ============================================================
// TOURSAFE — COMPLETE MOCK DATA
// Import this wherever needed. All data is static and realistic.
// (Unchanged from web app — pure data, no browser-only APIs used.)
// ============================================================

export const MOCK_ZONES = [
  // ─── TAMIL NADU ───────────────────────────────────────────
  {
    id: "zone-001",
    name: "Kodaikanal Lake & Boat Club Area",
    zone_type: "safe",
    center_lat: 10.2381,
    center_lng: 77.4892,
    radius_m: 800,
    alert_message_en: "You are in the Kodaikanal Lake safe zone. Police patrol active. Boat club operational 08:00–17:00.",
    alert_message_hi: "आप कोडाइकनाल झील सुरक्षित क्षेत्र में हैं। पुलिस गश्त सक्रिय है।",
    alert_message_ta: "நீங்கள் கொடைக்கானல் ஏரி பாதுகாப்பான மண்டலத்தில் உள்ளீர்கள். காவல் சுற்றுப்பயணம் செயலில் உள்ளது.",
    anomaly_threshold: 0.50,
    is_active: true,
    tourist_count: 47,
    active_alerts: 0,
  },
  {
    id: "zone-002",
    name: "Guna Caves (Devil's Kitchen)",
    zone_type: "danger",
    center_lat: 10.2167,
    center_lng: 77.4833,
    radius_m: 600,
    alert_message_en: "DANGER: Guna Caves is a restricted area. Deep crevices, unstable terrain. Entry strictly prohibited. Multiple fatalities reported.",
    alert_message_hi: "खतरा: गुना गुफाएं प्रतिबंधित क्षेत्र है। गहरी दरारें, अस्थिर भूभाग। प्रवेश सख्त वर्जित।",
    alert_message_ta: "ஆபத்து: குனா குகைகள் தடைசெய்யப்பட்ட பகுதி. ஆழமான இடைவெளிகள், நிலையற்ற நிலப்பரப்பு.",
    anomaly_threshold: 0.35,
    is_active: true,
    tourist_count: 3,
    active_alerts: 2,
  },
  {
    id: "zone-003",
    name: "Coaker's Walk Ridge Trail",
    zone_type: "warning",
    center_lat: 10.2291,
    center_lng: 77.4947,
    radius_m: 500,
    alert_message_en: "Warning: High altitude ridge trail at 2133m. No railings on northern sections. Mist reduces visibility. Stay on marked path.",
    alert_message_hi: "चेतावनी: 2133 मीटर पर उच्च ऊंचाई वाली रिज ट्रेल। उत्तरी भागों में कोई रेलिंग नहीं।",
    alert_message_ta: "எச்சரிக்கை: 2133 மீ உயரத்தில் மலை பாதை. வடக்கு பகுதிகளில் கம்பிகள் இல்லை.",
    anomaly_threshold: 0.60,
    is_active: true,
    tourist_count: 12,
    active_alerts: 1,
  },
  {
    id: "zone-004",
    name: "Berijam Lake Forest Reserve",
    zone_type: "restricted",
    center_lat: 10.1833,
    center_lng: 77.4167,
    radius_m: 1200,
    alert_message_en: "RESTRICTED: Tamil Nadu Forest Department protected area. Permit required at Kodaikanal Forest Office. Spotted deer and leopard habitat.",
    alert_message_hi: "प्रतिबंधित: तमिलनाडु वन विभाग संरक्षित क्षेत्र। परमिट आवश्यक है।",
    alert_message_ta: "தடைசெய்யப்பட்டது: தமிழ்நாடு வன திணைக்களம் பாதுகாக்கப்பட்ட பகுதி.",
    anomaly_threshold: 0.40,
    is_active: true,
    tourist_count: 0,
    active_alerts: 3,
  },
  {
    id: "zone-005",
    name: "Pillar Rocks Viewpoint",
    zone_type: "warning",
    center_lat: 10.2194,
    center_lng: 77.4736,
    radius_m: 400,
    alert_message_en: "Warning: 400-foot vertical rock pillars. Stay behind safety barriers. Do not attempt photography beyond the fence.",
    alert_message_ta: "எச்சரிக்கை: 400 அடி செங்குத்து பாறை தூண்கள். பாதுகாப்பு தடைகளுக்கு பின்னால் நில்லுங்கள்.",
    anomaly_threshold: 0.55,
    is_active: true,
    tourist_count: 18,
    active_alerts: 0,
  },
  {
    id: "zone-006",
    name: "Ooty Botanical Gardens",
    zone_type: "safe",
    center_lat: 11.4102,
    center_lng: 76.6950,
    radius_m: 700,
    alert_message_en: "Safe zone: Ooty Government Botanical Gardens. Open 07:00–18:30. Security guards on premises.",
    anomaly_threshold: 0.55,
    is_active: true,
    tourist_count: 89,
    active_alerts: 0,
  },
  {
    id: "zone-007",
    name: "Ooty Lake & Boathouse",
    zone_type: "safe",
    center_lat: 11.4000,
    center_lng: 76.7025,
    radius_m: 500,
    alert_message_en: "Ooty Lake safe zone. Life jackets mandatory for boating. No swimming in lake.",
    anomaly_threshold: 0.55,
    is_active: true,
    tourist_count: 62,
    active_alerts: 0,
  },
  {
    id: "zone-008",
    name: "Doddabetta Peak Summit",
    zone_type: "warning",
    center_lat: 11.4072,
    center_lng: 76.7350,
    radius_m: 600,
    alert_message_en: "Warning: Highest peak in Nilgiris at 2637m. Fog and cold winds common. Mobile signal weak. Inform authority before trekking.",
    anomaly_threshold: 0.65,
    is_active: true,
    tourist_count: 22,
    active_alerts: 1,
  },
  {
    id: "zone-009",
    name: "Pykara Lake & Waterfalls",
    zone_type: "warning",
    center_lat: 11.4455,
    center_lng: 76.6183,
    radius_m: 800,
    alert_message_en: "Warning: Slippery rocks near waterfalls. Strong current during monsoon. Keep children supervised at all times.",
    anomaly_threshold: 0.58,
    is_active: true,
    tourist_count: 34,
    active_alerts: 0,
  },
  {
    id: "zone-010",
    name: "Munnar Tea Gardens",
    zone_type: "safe",
    center_lat: 10.0892,
    center_lng: 77.0595,
    radius_m: 1000,
    alert_message_en: "Munnar tea garden safe zone. KDHP estate tour available 09:00–16:00. Stay on designated paths.",
    anomaly_threshold: 0.55,
    is_active: true,
    tourist_count: 71,
    active_alerts: 0,
  },
  {
    id: "zone-011",
    name: "Meesapulimala Trek Route",
    zone_type: "danger",
    center_lat: 10.0630,
    center_lng: 77.1000,
    radius_m: 1500,
    alert_message_en: "DANGER: Meesapulimala trek (2640m). Shola forest, sudden weather changes, wildlife encounters. Mandatory guide required. Register at Rhino Ranch.",
    anomaly_threshold: 0.40,
    is_active: true,
    tourist_count: 8,
    active_alerts: 1,
  },
  {
    id: "zone-012",
    name: "Palani Murugan Temple Complex",
    zone_type: "safe",
    center_lat: 10.4515,
    center_lng: 77.5191,
    radius_m: 600,
    alert_message_en: "Palani Murugan Temple safe zone. Crowd management in effect during festivals. Emergency medical post available.",
    anomaly_threshold: 0.55,
    is_active: true,
    tourist_count: 156,
    active_alerts: 0,
  },
  {
    id: "zone-013",
    name: "Courtallam Waterfalls (Main Falls)",
    zone_type: "warning",
    center_lat: 8.9347,
    center_lng: 77.2742,
    radius_m: 500,
    alert_message_en: "Warning: Strong water current at Courtallam. Swimming near fall strictly prohibited. Designated bathing areas only.",
    anomaly_threshold: 0.55,
    is_active: true,
    tourist_count: 43,
    active_alerts: 0,
  },
  {
    id: "zone-014",
    name: "Rameswaram Ramanathaswamy Temple",
    zone_type: "safe",
    center_lat: 9.2882,
    center_lng: 79.3175,
    radius_m: 700,
    alert_message_en: "Safe zone: Rameswaram temple complex. Dress code enforced. Security check at all entrances. Medical aid post available.",
    anomaly_threshold: 0.55,
    is_active: true,
    tourist_count: 234,
    active_alerts: 0,
  },
  {
    id: "zone-015",
    name: "Vattakanal & Dolphin's Nose",
    zone_type: "warning",
    center_lat: 10.2050,
    center_lng: 77.4650,
    radius_m: 700,
    alert_message_en: "Warning: Steep cliff at Dolphin's Nose. No safety barriers on cliff edge. Mist can arrive suddenly reducing visibility to near zero.",
    anomaly_threshold: 0.58,
    is_active: true,
    tourist_count: 15,
    active_alerts: 0,
  },

  // ─── NORTH INDIA ──────────────────────────────────────────
  {
    id: "zone-016",
    name: "Taj Mahal Complex, Agra",
    zone_type: "safe",
    center_lat: 27.1751,
    center_lng: 78.0421,
    radius_m: 800,
    alert_message_en: "Taj Mahal safe zone. CISF security deployed. No photography near minarets after 19:00. Medical post at east gate.",
    anomaly_threshold: 0.55,
    is_active: true,
    tourist_count: 412,
    active_alerts: 0,
  },
  {
    id: "zone-017",
    name: "Manali — Rohtang Pass Road",
    zone_type: "danger",
    center_lat: 32.2396,
    center_lng: 77.1887,
    radius_m: 2000,
    alert_message_en: "DANGER: Rohtang Pass (3978m). Avalanche risk, altitude sickness, sudden snowfall. Carry oxygen. Permit required from SDM Manali.",
    anomaly_threshold: 0.38,
    is_active: true,
    tourist_count: 19,
    active_alerts: 2,
  },
  {
    id: "zone-018",
    name: "Manali Old Town & Mall Road",
    zone_type: "safe",
    center_lat: 32.2396,
    center_lng: 77.1887,
    radius_m: 600,
    alert_message_en: "Manali town safe zone. Tourist police helpline: 01902-252374. Medical facilities at Lady Willingdon Hospital.",
    anomaly_threshold: 0.55,
    is_active: true,
    tourist_count: 88,
    active_alerts: 0,
  },
  {
    id: "zone-019",
    name: "Leh City & Shanti Stupa",
    zone_type: "warning",
    center_lat: 34.1526,
    center_lng: 77.5771,
    radius_m: 1000,
    alert_message_en: "Warning: Leh at 3500m altitude. Acclimatize for 48 hours before trekking. AMS (Altitude Mountain Sickness) risk. Oxygen available at SNM Hospital.",
    anomaly_threshold: 0.60,
    is_active: true,
    tourist_count: 53,
    active_alerts: 1,
  },
  {
    id: "zone-020",
    name: "Sangam Point, Leh (Frozen River)",
    zone_type: "danger",
    center_lat: 34.1000,
    center_lng: 77.5400,
    radius_m: 800,
    alert_message_en: "DANGER: Frozen river Sangam Point. Chadar Trek route. Ice thickness unpredictable. No individual access. Mandatory ALTOA guide.",
    anomaly_threshold: 0.35,
    is_active: true,
    tourist_count: 6,
    active_alerts: 1,
  },
  {
    id: "zone-021",
    name: "Rishikesh — Ram Jhula & Laxman Jhula",
    zone_type: "safe",
    center_lat: 30.1290,
    center_lng: 78.3214,
    radius_m: 700,
    alert_message_en: "Safe zone: Rishikesh. Tourist police active. River rafting operators licensed by Uttarakhand Tourism. Medical center at Triveni Ghat.",
    anomaly_threshold: 0.55,
    is_active: true,
    tourist_count: 127,
    active_alerts: 0,
  },
  {
    id: "zone-022",
    name: "Yamunotri Trek Route (Char Dham)",
    zone_type: "danger",
    center_lat: 31.0148,
    center_lng: 78.4558,
    radius_m: 2000,
    alert_message_en: "DANGER: Yamunotri pilgrimage route. Landslide risk during monsoon. Register at Hanuman Chatti before trekking. SDRF posted.",
    anomaly_threshold: 0.38,
    is_active: true,
    tourist_count: 34,
    active_alerts: 2,
  },
  {
    id: "zone-023",
    name: "Varanasi Ghats — Main Area",
    zone_type: "safe",
    center_lat: 25.3176,
    center_lng: 83.0104,
    radius_m: 900,
    alert_message_en: "Varanasi ghats safe zone. Tourist police desk at Dasaswamedh Ghat. Keep valuables secured. Medical post at Godaulia.",
    anomaly_threshold: 0.55,
    is_active: true,
    tourist_count: 198,
    active_alerts: 0,
  },
  {
    id: "zone-024",
    name: "Jaipur — Amber Fort Complex",
    zone_type: "safe",
    center_lat: 26.9855,
    center_lng: 75.8513,
    radius_m: 700,
    alert_message_en: "Amber Fort safe zone. ASI security deployed. Guide services at main gate. Medical post inside fort premises.",
    anomaly_threshold: 0.55,
    is_active: true,
    tourist_count: 231,
    active_alerts: 0,
  },
  {
    id: "zone-025",
    name: "Kedarnath Trek Route",
    zone_type: "danger",
    center_lat: 30.7346,
    center_lng: 79.0669,
    radius_m: 3000,
    alert_message_en: "DANGER: Kedarnath at 3583m. Flash flood risk. Register at Gaurikund. NDRF and SDRF deployed. Helicopter rescue available.",
    anomaly_threshold: 0.35,
    is_active: true,
    tourist_count: 28,
    active_alerts: 1,
  },
];

export const MOCK_TOURISTS = [
  {
    id: "tourist-001",
    user_id: "uid-001",
    full_name: "Vishal Lakshmikanthan",
    date_of_birth: "1996-03-15",
    nationality: "Indian",
    id_type: "aadhaar",
    phone_e164: "+919876543210",
    blood_type: "A+",
    medical_conditions: [],
    allergies: [],
    emergency_contact_name: "Rajesh Sharma",
    emergency_contact_phone: "+919876543211",
    emergency_contact_relation: "Father",
    preferred_language: "en",
    status: "sos",
    current_lat: 10.2291,
    current_lng: 77.4947,
    current_zone_id: "zone-003",
    tracking_consent: true,
    did_issued: true,
    did_mock_id: "TSX-PS-20240208",
    anomaly_score: 0.94,
    battery_pct: 62,
    last_seen: "2 min ago",
    age: 28,
  },
  {
    id: "tourist-002",
    user_id: "uid-002",
    full_name: "Raj Patel",
    date_of_birth: "1989-07-22",
    nationality: "Indian",
    id_type: "passport",
    phone_e164: "+919823456781",
    blood_type: "B+",
    medical_conditions: ["Type 2 Diabetes"],
    allergies: ["Penicillin"],
    emergency_contact_name: "Meena Patel",
    emergency_contact_phone: "+919823456782",
    emergency_contact_relation: "Wife",
    preferred_language: "hi",
    status: "warning",
    current_lat: 10.2150,
    current_lng: 77.4800,
    current_zone_id: "zone-002",
    tracking_consent: true,
    did_issued: true,
    did_mock_id: "TSX-RP-20240301",
    anomaly_score: 0.71,
    battery_pct: 45,
    last_seen: "45 sec ago",
    age: 35,
  },
  {
    id: "tourist-003",
    user_id: "uid-003",
    full_name: "Meena Das",
    date_of_birth: "1982-11-08",
    nationality: "Indian",
    id_type: "aadhaar",
    phone_e164: "+917654321098",
    blood_type: "O+",
    medical_conditions: ["Hypertension"],
    allergies: [],
    emergency_contact_name: "Suresh Das",
    emergency_contact_phone: "+917654321099",
    emergency_contact_relation: "Husband",
    preferred_language: "ta",
    status: "warning",
    current_lat: 10.1870,
    current_lng: 77.4200,
    current_zone_id: "zone-004",
    tracking_consent: true,
    did_issued: true,
    did_mock_id: "TSX-MD-20240210",
    anomaly_score: 0.63,
    battery_pct: 78,
    last_seen: "1 min ago",
    age: 42,
  },
  {
    id: "tourist-004",
    user_id: "uid-004",
    full_name: "Arjun Nair",
    date_of_birth: "1969-05-30",
    nationality: "Indian",
    id_type: "aadhaar",
    phone_e164: "+918765432109",
    blood_type: "AB+",
    medical_conditions: ["Hypertension", "Asthma"],
    allergies: ["Aspirin"],
    emergency_contact_name: "Lakshmi Nair",
    emergency_contact_phone: "+918765432110",
    emergency_contact_relation: "Wife",
    preferred_language: "ta",
    status: "safe",
    current_lat: 10.2400,
    current_lng: 77.4900,
    current_zone_id: "zone-001",
    tracking_consent: true,
    did_issued: true,
    did_mock_id: "TSX-AN-20240407",
    anomaly_score: 0.12,
    battery_pct: 91,
    last_seen: "28 sec ago",
    age: 55,
  },
  {
    id: "tourist-005",
    user_id: "uid-005",
    full_name: "Sarah Mitchell",
    date_of_birth: "1993-08-14",
    nationality: "British",
    id_type: "passport",
    phone_e164: "+447911123456",
    blood_type: "O-",
    medical_conditions: [],
    allergies: ["Nuts", "Latex"],
    emergency_contact_name: "James Mitchell",
    emergency_contact_phone: "+447911123457",
    emergency_contact_relation: "Brother",
    preferred_language: "en",
    status: "safe",
    current_lat: 10.2350,
    current_lng: 77.4880,
    current_zone_id: "zone-001",
    tracking_consent: true,
    did_issued: false,
    did_mock_id: null,
    anomaly_score: 0.08,
    battery_pct: 55,
    last_seen: "1 min ago",
    age: 31,
  },
  {
    id: "tourist-006",
    user_id: "uid-006",
    full_name: "Arun Kumar",
    date_of_birth: "1995-12-20",
    nationality: "Indian",
    id_type: "aadhaar",
    phone_e164: "+919988776655",
    blood_type: "O+",
    medical_conditions: [],
    allergies: [],
    emergency_contact_name: "Vijay Kumar",
    emergency_contact_phone: "+919988776656",
    emergency_contact_relation: "Father",
    preferred_language: "en",
    status: "safe",
    current_lat: 10.2320,
    current_lng: 77.4860,
    current_zone_id: "zone-001",
    tracking_consent: true,
    did_issued: true,
    did_mock_id: "TSX-AK-20240409",
    anomaly_score: 0.10,
    battery_pct: 83,
    last_seen: "30 sec ago",
    age: 29,
  },
  {
    id: "tourist-007",
    user_id: "uid-007",
    full_name: "Chen Wei",
    date_of_birth: "1990-04-05",
    nationality: "Chinese",
    id_type: "passport",
    phone_e164: "+8613812345678",
    blood_type: "B+",
    medical_conditions: [],
    allergies: [],
    emergency_contact_name: "Chen Liu",
    emergency_contact_phone: "+8613812345679",
    emergency_contact_relation: "Spouse",
    preferred_language: "en",
    status: "safe",
    current_lat: 10.2190,
    current_lng: 77.4736,
    current_zone_id: "zone-005",
    tracking_consent: true,
    did_issued: true,
    did_mock_id: "TSX-CW-20240310",
    anomaly_score: 0.15,
    battery_pct: 67,
    last_seen: "2 min ago",
    age: 34,
  },
  {
    id: "tourist-008",
    user_id: "uid-008",
    full_name: "Maria Rodriguez",
    date_of_birth: "1988-09-17",
    nationality: "Spanish",
    id_type: "passport",
    phone_e164: "+34612345678",
    blood_type: "A-",
    medical_conditions: ["Epilepsy"],
    allergies: [],
    emergency_contact_name: "Carlos Rodriguez",
    emergency_contact_phone: "+34612345679",
    emergency_contact_relation: "Brother",
    preferred_language: "en",
    status: "active",
    current_lat: 10.2360,
    current_lng: 77.4920,
    current_zone_id: "zone-001",
    tracking_consent: true,
    did_issued: true,
    did_mock_id: "TSX-MR-20240315",
    anomaly_score: 0.18,
    battery_pct: 72,
    last_seen: "45 sec ago",
    age: 36,
  },
  {
    id: "tourist-009",
    user_id: "uid-009",
    full_name: "Vikram Singh",
    date_of_birth: "1978-02-28",
    nationality: "Indian",
    id_type: "aadhaar",
    phone_e164: "+911122334455",
    blood_type: "B-",
    medical_conditions: ["Heart condition — mild arrhythmia"],
    allergies: ["Sulfa drugs"],
    emergency_contact_name: "Kavitha Singh",
    emergency_contact_phone: "+911122334456",
    emergency_contact_relation: "Wife",
    preferred_language: "hi",
    status: "safe",
    current_lat: 10.2050,
    current_lng: 77.4650,
    current_zone_id: "zone-015",
    tracking_consent: true,
    did_issued: true,
    did_mock_id: "TSX-VS-20240320",
    anomaly_score: 0.22,
    battery_pct: 38,
    last_seen: "3 min ago",
    age: 46,
  },
  {
    id: "tourist-010",
    user_id: "uid-010",
    full_name: "Ananya Krishnamurthy",
    date_of_birth: "2001-06-12",
    nationality: "Indian",
    id_type: "aadhaar",
    phone_e164: "+919977665544",
    blood_type: "A+",
    medical_conditions: [],
    allergies: [],
    emergency_contact_name: "Raghunath Krishnamurthy",
    emergency_contact_phone: "+919977665545",
    emergency_contact_relation: "Father",
    preferred_language: "ta",
    status: "safe",
    current_lat: 10.2410,
    current_lng: 77.4870,
    current_zone_id: "zone-001",
    tracking_consent: true,
    did_issued: true,
    did_mock_id: "TSX-AK2-20240402",
    anomaly_score: 0.07,
    battery_pct: 94,
    last_seen: "1 min ago",
    age: 23,
  },
  {
    id: "tourist-011",
    user_id: "uid-011",
    full_name: "David Thompson",
    date_of_birth: "1975-11-03",
    nationality: "American",
    id_type: "passport",
    phone_e164: "+14155557890",
    blood_type: "O+",
    medical_conditions: ["Type 1 Diabetes"],
    allergies: ["Ibuprofen"],
    emergency_contact_name: "Susan Thompson",
    emergency_contact_phone: "+14155557891",
    emergency_contact_relation: "Wife",
    preferred_language: "en",
    status: "safe",
    current_lat: 10.2375,
    current_lng: 77.4910,
    current_zone_id: "zone-001",
    tracking_consent: true,
    did_issued: true,
    did_mock_id: "TSX-DT-20240318",
    anomaly_score: 0.11,
    battery_pct: 61,
    last_seen: "2 min ago",
    age: 49,
  },
  {
    id: "tourist-012",
    user_id: "uid-012",
    full_name: "Fatima Al-Rashidi",
    date_of_birth: "1991-01-25",
    nationality: "Emirati",
    id_type: "passport",
    phone_e164: "+971501234567",
    blood_type: "AB+",
    medical_conditions: [],
    allergies: [],
    emergency_contact_name: "Mohammed Al-Rashidi",
    emergency_contact_phone: "+971501234568",
    emergency_contact_relation: "Husband",
    preferred_language: "en",
    status: "active",
    current_lat: 10.2340,
    current_lng: 77.4895,
    current_zone_id: "zone-001",
    tracking_consent: true,
    did_issued: true,
    did_mock_id: "TSX-FA-20240325",
    anomaly_score: 0.09,
    battery_pct: 88,
    last_seen: "30 sec ago",
    age: 33,
  },
  {
    id: "tourist-013",
    user_id: "uid-013",
    full_name: "Hiroshi Tanaka",
    date_of_birth: "1983-09-08",
    nationality: "Japanese",
    id_type: "passport",
    phone_e164: "+819012345678",
    blood_type: "A+",
    medical_conditions: [],
    allergies: [],
    emergency_contact_name: "Yuki Tanaka",
    emergency_contact_phone: "+819012345679",
    emergency_contact_relation: "Wife",
    preferred_language: "en",
    status: "safe",
    current_lat: 10.2180,
    current_lng: 77.4750,
    current_zone_id: "zone-005",
    tracking_consent: true,
    did_issued: true,
    did_mock_id: "TSX-HT-20240412",
    anomaly_score: 0.13,
    battery_pct: 79,
    last_seen: "1 min ago",
    age: 41,
  },
  {
    id: "tourist-014",
    user_id: "uid-014",
    full_name: "Sunita Reddy",
    date_of_birth: "1987-04-18",
    nationality: "Indian",
    id_type: "aadhaar",
    phone_e164: "+918866554433",
    blood_type: "B+",
    medical_conditions: [],
    allergies: [],
    emergency_contact_name: "Ramesh Reddy",
    emergency_contact_phone: "+918866554434",
    emergency_contact_relation: "Brother",
    preferred_language: "en",
    status: "safe",
    current_lat: 10.2270,
    current_lng: 77.4930,
    current_zone_id: "zone-003",
    tracking_consent: true,
    did_issued: false,
    did_mock_id: null,
    anomaly_score: 0.20,
    battery_pct: 52,
    last_seen: "2 min ago",
    age: 37,
  },
  {
    id: "tourist-015",
    user_id: "uid-015",
    full_name: "Klaus Müller",
    date_of_birth: "1970-07-14",
    nationality: "German",
    id_type: "passport",
    phone_e164: "+4915123456789",
    blood_type: "O-",
    medical_conditions: ["Pacemaker"],
    allergies: [],
    emergency_contact_name: "Greta Müller",
    emergency_contact_phone: "+4915123456790",
    emergency_contact_relation: "Wife",
    preferred_language: "en",
    status: "alert",
    current_lat: 10.2170,
    current_lng: 77.4840,
    current_zone_id: "zone-002",
    tracking_consent: true,
    did_issued: true,
    did_mock_id: "TSX-KM-20240328",
    anomaly_score: 0.78,
    battery_pct: 24,
    last_seen: "4 min ago",
    age: 54,
  },
  {
    id: "tourist-016",
    user_id: "uid-016",
    full_name: "Pooja Iyer",
    date_of_birth: "1999-10-22",
    nationality: "Indian",
    id_type: "aadhaar",
    phone_e164: "+917755443322",
    blood_type: "O+",
    medical_conditions: [],
    allergies: [],
    emergency_contact_name: "Raman Iyer",
    emergency_contact_phone: "+917755443323",
    emergency_contact_relation: "Father",
    preferred_language: "ta",
    status: "safe",
    current_lat: 10.2390,
    current_lng: 77.4870,
    current_zone_id: "zone-001",
    tracking_consent: true,
    did_issued: true,
    did_mock_id: "TSX-PI-20240405",
    anomaly_score: 0.06,
    battery_pct: 97,
    last_seen: "25 sec ago",
    age: 25,
  },
  {
    id: "tourist-017",
    user_id: "uid-017",
    full_name: "Robert Chen",
    date_of_birth: "1985-03-11",
    nationality: "Singaporean",
    id_type: "passport",
    phone_e164: "+6591234567",
    blood_type: "A+",
    medical_conditions: [],
    allergies: ["Shellfish"],
    emergency_contact_name: "Linda Chen",
    emergency_contact_phone: "+6591234568",
    emergency_contact_relation: "Sister",
    preferred_language: "en",
    status: "safe",
    current_lat: 10.2310,
    current_lng: 77.4910,
    current_zone_id: "zone-001",
    tracking_consent: true,
    did_issued: true,
    did_mock_id: "TSX-RC-20240401",
    anomaly_score: 0.16,
    battery_pct: 70,
    last_seen: "1 min ago",
    age: 39,
  },
  {
    id: "tourist-018",
    user_id: "uid-018",
    full_name: "Kavitha Subramaniam",
    date_of_birth: "1994-08-05",
    nationality: "Indian",
    id_type: "aadhaar",
    phone_e164: "+916655443322",
    blood_type: "B+",
    medical_conditions: [],
    allergies: [],
    emergency_contact_name: "Subramaniam P.",
    emergency_contact_phone: "+916655443323",
    emergency_contact_relation: "Father",
    preferred_language: "ta",
    status: "safe",
    current_lat: 10.2280,
    current_lng: 77.4940,
    current_zone_id: "zone-003",
    tracking_consent: false,
    did_issued: false,
    did_mock_id: null,
    anomaly_score: 0.0,
    battery_pct: 66,
    last_seen: "Tracking off",
    age: 30,
  },
  {
    id: "tourist-019",
    user_id: "uid-019",
    full_name: "Amit Joshi",
    date_of_birth: "1992-12-01",
    nationality: "Indian",
    id_type: "aadhaar",
    phone_e164: "+913344556677",
    blood_type: "AB-",
    medical_conditions: [],
    allergies: [],
    emergency_contact_name: "Prerna Joshi",
    emergency_contact_phone: "+913344556678",
    emergency_contact_relation: "Wife",
    preferred_language: "hi",
    status: "safe",
    current_lat: 10.2420,
    current_lng: 77.4860,
    current_zone_id: "zone-001",
    tracking_consent: true,
    did_issued: true,
    did_mock_id: "TSX-AJ-20240408",
    anomaly_score: 0.09,
    battery_pct: 85,
    last_seen: "40 sec ago",
    age: 32,
  },
  {
    id: "tourist-020",
    user_id: "uid-020",
    full_name: "Isabella Rossi",
    date_of_birth: "1997-05-23",
    nationality: "Italian",
    id_type: "passport",
    phone_e164: "+393312345678",
    blood_type: "A+",
    medical_conditions: [],
    allergies: [],
    emergency_contact_name: "Marco Rossi",
    emergency_contact_phone: "+393312345679",
    emergency_contact_relation: "Father",
    preferred_language: "en",
    status: "safe",
    current_lat: 10.2255,
    current_lng: 77.4960,
    current_zone_id: "zone-003",
    tracking_consent: true,
    did_issued: true,
    did_mock_id: "TSX-IR-20240410",
    anomaly_score: 0.14,
    battery_pct: 58,
    last_seen: "2 min ago",
    age: 27,
  },
];

export const MOCK_ALERTS = [
  {
    id: "alert-001",
    tourist_id: "tourist-001",
    tourist: MOCK_TOURISTS[0],
    alert_type: "sos",
    severity: "critical",
    latitude: 10.2291,
    longitude: 77.4947,
    zone_id: "zone-003",
    zone_name: "Coaker's Walk Ridge Trail",
    anomaly_score: 0.94,
    description: "SOS triggered by Vishal Lakshmikanthan at Coaker's Walk Ridge. Tourist stationary for 3 minutes 24 seconds. Blood type: A+. Trigger: Hold button.",
    status: "new",
    assigned_to: null,
    acknowledged_at: null,
    resolved_at: null,
    resolution_notes: null,
    created_at: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
  },
  {
    id: "alert-002",
    tourist_id: "tourist-002",
    tourist: MOCK_TOURISTS[1],
    alert_type: "anomaly",
    severity: "high",
    latitude: 10.2150,
    longitude: 77.4800,
    zone_id: "zone-002",
    zone_name: "Guna Caves (Devil's Kitchen)",
    anomaly_score: 0.71,
    description: "High anomaly score (0.71) detected for Raj Patel near Guna Caves. Tourist route deviated 450m from expected path. Approaching restricted area boundary.",
    status: "new",
    assigned_to: null,
    acknowledged_at: null,
    resolved_at: null,
    resolution_notes: null,
    created_at: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
  },
  {
    id: "alert-003",
    tourist_id: "tourist-003",
    tourist: MOCK_TOURISTS[2],
    alert_type: "geofence_breach",
    severity: "high",
    latitude: 10.1870,
    longitude: 77.4200,
    zone_id: "zone-004",
    zone_name: "Berijam Lake Forest Reserve",
    anomaly_score: null,
    description: "Tourist Meena Das entered Berijam Lake Forest Reserve restricted zone without permit. Forest Department area. Immediate exit requested. Tourist notified via in-app alert.",
    status: "acknowledged",
    assigned_to: "auth-001",
    acknowledged_at: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
    resolved_at: null,
    resolution_notes: null,
    created_at: new Date(Date.now() - 24 * 60 * 1000).toISOString(),
  },
  {
    id: "alert-004",
    tourist_id: "tourist-015",
    tourist: MOCK_TOURISTS[14],
    alert_type: "anomaly",
    severity: "high",
    latitude: 10.2170,
    longitude: 77.4840,
    zone_id: "zone-002",
    zone_name: "Guna Caves (Devil's Kitchen)",
    anomaly_score: 0.78,
    description: "High anomaly score (0.78) for Klaus Müller near Guna Caves. Tourist has pacemaker. Sudden inactivity detected after 20 minutes of normal movement. Low battery warning: 24%.",
    status: "new",
    assigned_to: null,
    acknowledged_at: null,
    resolved_at: null,
    resolution_notes: null,
    created_at: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
  },
  {
    id: "alert-005",
    tourist_id: "tourist-009",
    tourist: MOCK_TOURISTS[8],
    alert_type: "low_battery",
    severity: "low",
    latitude: 10.2050,
    longitude: 77.4650,
    zone_id: "zone-015",
    zone_name: "Vattakanal & Dolphin's Nose",
    anomaly_score: null,
    description: "Tourist Vikram Singh device battery at 38%. Tracking may be interrupted soon. Tourist has heart condition. Last known location: Vattakanal viewpoint.",
    status: "new",
    assigned_to: null,
    acknowledged_at: null,
    resolved_at: null,
    resolution_notes: null,
    created_at: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
  },
  {
    id: "alert-006",
    tourist_id: "tourist-004",
    tourist: MOCK_TOURISTS[3],
    alert_type: "inactivity",
    severity: "medium",
    latitude: 10.2400,
    longitude: 77.4900,
    zone_id: "zone-001",
    zone_name: "Kodaikanal Lake Area",
    anomaly_score: 0.42,
    description: "Tourist Arjun Nair stationary for 18 minutes at Kodaikanal Lake viewpoint. No SOS triggered. Tourist confirmed resting via app check-in. Battery: 91%.",
    status: "resolved",
    assigned_to: "auth-001",
    acknowledged_at: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
    resolved_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    resolution_notes: "Tourist Arjun Nair confirmed resting at lakeside bench. Status normal. Alert closed.",
    created_at: new Date(Date.now() - 62 * 60 * 1000).toISOString(),
  },
  {
    id: "alert-007",
    tourist_id: "tourist-007",
    tourist: MOCK_TOURISTS[6],
    alert_type: "geofence_breach",
    severity: "medium",
    latitude: 10.2190,
    longitude: 77.4736,
    zone_id: "zone-005",
    zone_name: "Pillar Rocks Viewpoint",
    anomaly_score: null,
    description: "Tourist Chen Wei approached safety barrier perimeter at Pillar Rocks. Entered 30m buffer zone. Tourist notified. No barrier breach.",
    status: "false_positive",
    assigned_to: "auth-001",
    acknowledged_at: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    resolved_at: new Date(Date.now() - 85 * 60 * 1000).toISOString(),
    resolution_notes: "Tourist was on designated viewing platform. False positive — GPS accuracy issue caused apparent boundary breach.",
    created_at: new Date(Date.now() - 95 * 60 * 1000).toISOString(),
  },
  {
    id: "alert-008",
    tourist_id: "tourist-008",
    tourist: MOCK_TOURISTS[7],
    alert_type: "anomaly",
    severity: "medium",
    latitude: 10.2360,
    longitude: 77.4920,
    zone_id: "zone-001",
    zone_name: "Kodaikanal Lake Area",
    anomaly_score: 0.58,
    description: "Moderate anomaly score (0.58) for Maria Rodriguez. Tourist has epilepsy. Unusual circular movement pattern detected near lakeside. Speed: 0.2 km/h for 12 minutes.",
    status: "new",
    assigned_to: null,
    acknowledged_at: null,
    resolved_at: null,
    resolution_notes: null,
    created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
];

export const MOCK_INCIDENTS = [
  {
    id: "incident-001",
    alert_id: "alert-001",
    tourist_id: "tourist-001",
    tourist: MOCK_TOURISTS[0],
    incident_type: "accident",
    priority: "critical",
    latitude: 10.2291,
    longitude: 77.4947,
    location_name: "Coaker's Walk Ridge Trail, Kodaikanal",
    description: "SOS triggered by tourist Vishal Lakshmikanthan at Coaker's Walk Ridge. Tourist appears to have slipped on wet trail. Last movement detected 3+ minutes ago. SOS trigger type: hold button.",
    status: "open",
    assigned_authority_id: null,
    efir_id: null,
    created_at: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    resolved_at: null,
  },
  {
    id: "incident-002",
    alert_id: "alert-003",
    tourist_id: "tourist-003",
    tourist: MOCK_TOURISTS[2],
    incident_type: "other",
    priority: "medium",
    latitude: 10.1870,
    longitude: 77.4200,
    location_name: "Berijam Lake Reserve Boundary, Kodaikanal",
    description: "Tourist Meena Das entered restricted forest reserve without permit. Approached ranger checkpoint. Needs escorted exit from Berijam Lake area.",
    status: "responding",
    assigned_authority_id: "auth-001",
    efir_id: null,
    created_at: new Date(Date.now() - 24 * 60 * 1000).toISOString(),
    resolved_at: null,
  },
  {
    id: "incident-003",
    alert_id: "alert-004",
    tourist_id: "tourist-015",
    tourist: MOCK_TOURISTS[14],
    incident_type: "medical",
    priority: "high",
    latitude: 10.2170,
    longitude: 77.4840,
    location_name: "Near Guna Caves, Kodaikanal",
    description: "Tourist Klaus Müller with pacemaker showing anomalous movement near Guna Caves danger zone. Battery critical (24%). Medical attention may be required. German national — has travel insurance.",
    status: "open",
    assigned_authority_id: null,
    efir_id: null,
    created_at: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    resolved_at: null,
  },
  {
    id: "incident-004",
    alert_id: "alert-006",
    tourist_id: "tourist-004",
    tourist: MOCK_TOURISTS[3],
    incident_type: "other",
    priority: "low",
    latitude: 10.2400,
    longitude: 77.4900,
    location_name: "Kodaikanal Lake Viewpoint",
    description: "Inactivity alert for senior tourist Arjun Nair. Tourist resting at lakeside bench. Verified safe via phone contact. No action required.",
    status: "closed",
    assigned_authority_id: "auth-001",
    efir_id: null,
    created_at: new Date(Date.now() - 62 * 60 * 1000).toISOString(),
    resolved_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
];

export const MOCK_EFIRS = [
  {
    id: "efir-001",
    incident_id: "incident-002",
    tourist_id: "tourist-003",
    tourist: MOCK_TOURISTS[2],
    case_number: "TSX-20260414-A7F3B2",
    fir_type: "Trespass — Restricted Area",
    complainant_name: "Meena Das",
    complainant_nationality: "Indian",
    incident_date: new Date(Date.now() - 24 * 60 * 1000).toISOString(),
    incident_location_text: "Berijam Lake Forest Reserve, Kodaikanal, Tamil Nadu — 10.1870°N, 77.4200°E",
    incident_description: "Tourist Meena Das (Indian national, Aadhaar ID, Blood: O+, Hypertension) entered Berijam Lake Forest Reserve restricted area at 08:18 IST on 14-Apr-2026 without obtaining mandatory Forest Department permit from Kodaikanal Forest Office. Tourist was detected via TourSafe geofence alert. TNPOL patrol contacted tourist at entry point. Tourist was escorted back to the main road without incident.",
    authority_notes: "Tourist was unaware of permit requirement. Verbal warning issued. Tourist advised to obtain permit for future visits. No damage to forest area. Case recommended for closure.",
    status: "approved",
    created_by: "auth-001",
    pdf_url: null,
    created_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
  },
  {
    id: "efir-002",
    incident_id: "incident-001",
    tourist_id: "tourist-001",
    tourist: MOCK_TOURISTS[0],
    case_number: "TSX-20260414-C9D1E5",
    fir_type: "SOS — Possible Accident",
    complainant_name: "Vishal Lakshmikanthan",
    complainant_nationality: "Indian",
    incident_date: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    incident_location_text: "Coaker's Walk Ridge Trail, Kodaikanal, Tamil Nadu — 10.2291°N, 77.4947°E",
    incident_description: "Tourist Vishal Lakshmikanthan (Indian national, Blood: A+) triggered SOS via TourSafe hold button at 09:39 IST on 14-Apr-2026 at Coaker's Walk Ridge Trail. Tourist stationary for 3 minutes 24 seconds prior to SOS. Anomaly score: 0.94/1.00. SDRF and police notified. Search and rescue operation initiated.",
    authority_notes: null,
    status: "draft",
    created_by: "auth-001",
    pdf_url: null,
    created_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
  },
  {
    id: "efir-003",
    incident_id: "incident-004",
    tourist_id: "tourist-004",
    tourist: MOCK_TOURISTS[3],
    case_number: "TSX-20260413-B2F7A1",
    fir_type: "Inactivity Pre-Alert — Closed",
    complainant_name: "Arjun Nair",
    complainant_nationality: "Indian",
    incident_date: new Date(Date.now() - 62 * 60 * 1000).toISOString(),
    incident_location_text: "Kodaikanal Lake Viewpoint — 10.2400°N, 77.4900°E",
    incident_description: "Inactivity alert triggered for tourist Arjun Nair (Indian, Blood: AB+, Hypertension + Asthma). Tourist was stationary for 18 minutes at lakeside viewpoint bench. Authority contacted tourist via phone. Tourist confirmed resting and safe. No medical emergency. Alert resolved.",
    authority_notes: "Tourist Arjun Nair (55, male) confirmed resting. Advised to inform family. Case closed — no incident.",
    status: "closed",
    created_by: "auth-001",
    pdf_url: null,
    created_at: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
];

export const MOCK_AUTHORITY = {
  id: "auth-001",
  user_id: "uid-auth-001",
  full_name: "Kumar Rajendran",
  badge_number: "TNPOL-KDL-001",
  station_name: "Kodaikanal Police Station",
  station_code: "KDL-PS",
  phone_e164: "+914542241100",
  zone_id: "zone-001",
  role: "zone_authority",
};

export const MOCK_AUTHORITIES = [
  {
    id: "auth-001",
    full_name: "Kumar Rajendran",
    badge_number: "TNPOL-KDL-001",
    station_name: "Kodaikanal Police Station",
    role: "zone_authority",
    is_active: true,
  },
  {
    id: "auth-002",
    full_name: "Suresh Babu",
    badge_number: "TNPOL-KDL-002",
    station_name: "Kodaikanal Forest Police",
    role: "field_responder",
    is_active: true,
  },
  {
    id: "auth-003",
    full_name: "Lakshmi Devi",
    badge_number: "TNPOL-KDL-003",
    station_name: "Kodaikanal Tourist Police",
    role: "supervisor",
    is_active: true,
  },
  {
    id: "auth-004",
    full_name: "Pandiarajan M.",
    badge_number: "SDRF-TN-041",
    station_name: "SDRF Unit — Palani",
    role: "field_responder",
    is_active: true,
  },
];

export const MOCK_KPI = {
  total_active: 47,
  status_breakdown: { safe: 43, warning: 3, alert: 0, sos: 1, active: 0 },
  avg_response_time_minutes: 7.2,
  alerts_today: 8,
  alert_type_breakdown: {
    anomaly: 4,
    geofence_breach: 2,
    sos: 1,
    inactivity: 1,
    low_battery: 0,
  },
  false_positive_rate: 12.5,
  did_adoption_pct: 62,
};

export const MOCK_RESPONSE_TIMES = [
  { date: "Apr 08", avg_minutes: 12.4, count: 3 },
  { date: "Apr 09", avg_minutes: 9.1,  count: 5 },
  { date: "Apr 10", avg_minutes: 14.8, count: 2 },
  { date: "Apr 11", avg_minutes: 7.5,  count: 6 },
  { date: "Apr 12", avg_minutes: 8.9,  count: 4 },
  { date: "Apr 13", avg_minutes: 6.3,  count: 7 },
  { date: "Apr 14", avg_minutes: 7.2,  count: 3 },
];

export const MOCK_INCIDENT_TRENDS = [
  { week: "2026-W06", counts: { missing: 0, accident: 1, medical: 0, crime: 0, other: 2 } },
  { week: "2026-W07", counts: { missing: 0, accident: 0, medical: 1, crime: 0, other: 1 } },
  { week: "2026-W08", counts: { missing: 1, accident: 1, medical: 0, crime: 1, other: 0 } },
  { week: "2026-W09", counts: { missing: 0, accident: 2, medical: 1, crime: 0, other: 1 } },
  { week: "2026-W10", counts: { missing: 0, accident: 0, medical: 0, crime: 0, other: 3 } },
  { week: "2026-W11", counts: { missing: 0, accident: 1, medical: 2, crime: 0, other: 1 } },
  { week: "2026-W12", counts: { missing: 1, accident: 0, medical: 1, crime: 1, other: 0 } },
  { week: "2026-W13", counts: { missing: 0, accident: 1, medical: 0, crime: 0, other: 2 } },
];

export const MOCK_TOURIST_FLOW = [
  { hour: "06:00", entries: 2,  exits: 0  },
  { hour: "07:00", entries: 8,  exits: 1  },
  { hour: "08:00", entries: 14, exits: 3  },
  { hour: "09:00", entries: 22, exits: 5  },
  { hour: "10:00", entries: 31, exits: 8  },
  { hour: "11:00", entries: 18, exits: 12 },
  { hour: "12:00", entries: 9,  exits: 15 },
  { hour: "13:00", entries: 12, exits: 11 },
  { hour: "14:00", entries: 25, exits: 9  },
  { hour: "15:00", entries: 19, exits: 14 },
  { hour: "16:00", entries: 11, exits: 22 },
  { hour: "17:00", entries: 4,  exits: 31 },
  { hour: "18:00", entries: 1,  exits: 18 },
  { hour: "19:00", entries: 0,  exits: 7  },
];

export const MOCK_HEATMAP_POINTS: [number, number, number][] = [
  // Kodaikanal Lake (dense cluster)
  [10.2381, 77.4892, 0.9], [10.2390, 77.4880, 0.85], [10.2375, 77.4905, 0.8],
  [10.2365, 77.4915, 0.75], [10.2395, 77.4870, 0.7], [10.2340, 77.4895, 0.65],
  [10.2350, 77.4880, 0.7], [10.2410, 77.4860, 0.6], [10.2420, 77.4870, 0.55],
  [10.2330, 77.4910, 0.6], [10.2310, 77.4925, 0.5], [10.2355, 77.4935, 0.55],
  // Coaker's Walk
  [10.2291, 77.4947, 0.8], [10.2280, 77.4940, 0.65], [10.2270, 77.4930, 0.5],
  [10.2265, 77.4960, 0.45], [10.2300, 77.4955, 0.5],
  // Pillar Rocks
  [10.2194, 77.4736, 0.7], [10.2185, 77.4745, 0.6], [10.2200, 77.4725, 0.55],
  [10.2210, 77.4740, 0.5], [10.2180, 77.4755, 0.45],
  // Vattakanal
  [10.2050, 77.4650, 0.5], [10.2060, 77.4660, 0.4], [10.2040, 77.4640, 0.35],
  // Guna Caves (danger, few but present)
  [10.2167, 77.4833, 0.6], [10.2155, 77.4820, 0.5], [10.2178, 77.4845, 0.4],
  // Berijam entry
  [10.1870, 77.4200, 0.4], [10.1880, 77.4210, 0.35],
];

export const MOCK_LOCATION_HISTORY = [
  { latitude: 10.2381, longitude: 77.4892, speed_kmh: 4.2, altitude_m: 2133, anomaly_score: 0.08, battery_pct: 74, recorded_at: new Date(Date.now() - 0.5 * 60 * 1000).toISOString() },
  { latitude: 10.2378, longitude: 77.4889, speed_kmh: 3.8, altitude_m: 2133, anomaly_score: 0.09, battery_pct: 75, recorded_at: new Date(Date.now() - 1 * 60 * 1000).toISOString() },
  { latitude: 10.2374, longitude: 77.4885, speed_kmh: 5.1, altitude_m: 2134, anomaly_score: 0.07, battery_pct: 75, recorded_at: new Date(Date.now() - 1.5 * 60 * 1000).toISOString() },
  { latitude: 10.2370, longitude: 77.4880, speed_kmh: 4.5, altitude_m: 2135, anomaly_score: 0.10, battery_pct: 76, recorded_at: new Date(Date.now() - 2 * 60 * 1000).toISOString() },
  { latitude: 10.2365, longitude: 77.4876, speed_kmh: 3.9, altitude_m: 2136, anomaly_score: 0.08, battery_pct: 76, recorded_at: new Date(Date.now() - 2.5 * 60 * 1000).toISOString() },
  { latitude: 10.2360, longitude: 77.4872, speed_kmh: 4.8, altitude_m: 2137, anomaly_score: 0.09, battery_pct: 76, recorded_at: new Date(Date.now() - 3 * 60 * 1000).toISOString() },
  { latitude: 10.2355, longitude: 77.4868, speed_kmh: 3.2, altitude_m: 2137, anomaly_score: 0.11, battery_pct: 77, recorded_at: new Date(Date.now() - 3.5 * 60 * 1000).toISOString() },
  { latitude: 10.2350, longitude: 77.4864, speed_kmh: 4.0, altitude_m: 2136, anomaly_score: 0.08, battery_pct: 77, recorded_at: new Date(Date.now() - 4 * 60 * 1000).toISOString() },
  { latitude: 10.2344, longitude: 77.4860, speed_kmh: 5.5, altitude_m: 2135, anomaly_score: 0.07, battery_pct: 77, recorded_at: new Date(Date.now() - 4.5 * 60 * 1000).toISOString() },
  { latitude: 10.2338, longitude: 77.4856, speed_kmh: 4.1, altitude_m: 2134, anomaly_score: 0.10, battery_pct: 78, recorded_at: new Date(Date.now() - 5 * 60 * 1000).toISOString() },
  { latitude: 10.2332, longitude: 77.4851, speed_kmh: 3.7, altitude_m: 2133, anomaly_score: 0.09, battery_pct: 78, recorded_at: new Date(Date.now() - 5.5 * 60 * 1000).toISOString() },
  { latitude: 10.2326, longitude: 77.4847, speed_kmh: 4.3, altitude_m: 2133, anomaly_score: 0.08, battery_pct: 78, recorded_at: new Date(Date.now() - 6 * 60 * 1000).toISOString() },
  { latitude: 10.2320, longitude: 77.4843, speed_kmh: 3.5, altitude_m: 2132, anomaly_score: 0.12, battery_pct: 79, recorded_at: new Date(Date.now() - 6.5 * 60 * 1000).toISOString() },
  { latitude: 10.2314, longitude: 77.4840, speed_kmh: 4.7, altitude_m: 2132, anomaly_score: 0.09, battery_pct: 79, recorded_at: new Date(Date.now() - 7 * 60 * 1000).toISOString() },
  { latitude: 10.2308, longitude: 77.4837, speed_kmh: 4.0, altitude_m: 2131, anomaly_score: 0.08, battery_pct: 79, recorded_at: new Date(Date.now() - 7.5 * 60 * 1000).toISOString() },
];

export const MOCK_ZONE_SUMMARY = [
  { id: "zone-001", name: "Kodaikanal Lake", zone_type: "safe",       is_active: true, tourist_count: 47, active_alerts: 0, avg_response_minutes: 6.1  },
  { id: "zone-002", name: "Guna Caves",       zone_type: "danger",     is_active: true, tourist_count: 3,  active_alerts: 2, avg_response_minutes: 9.4  },
  { id: "zone-003", name: "Coaker's Walk",    zone_type: "warning",    is_active: true, tourist_count: 12, active_alerts: 1, avg_response_minutes: 7.8  },
  { id: "zone-004", name: "Berijam Lake",     zone_type: "restricted", is_active: true, tourist_count: 0,  active_alerts: 3, avg_response_minutes: 14.2 },
  { id: "zone-005", name: "Pillar Rocks",     zone_type: "warning",    is_active: true, tourist_count: 18, active_alerts: 0, avg_response_minutes: 5.9  },
  { id: "zone-015", name: "Vattakanal",       zone_type: "warning",    is_active: true, tourist_count: 15, active_alerts: 0, avg_response_minutes: 8.3  },
];

export const MOCK_CONSENTS = [
  { id: "consent-001", tourist_id: "tourist-logged-in", consent_type: "gps_tracking",                    is_granted: true,  granted_at: "2026-04-12T14:32:00Z", revoked_at: null },
  { id: "consent-002", tourist_id: "tourist-logged-in", consent_type: "digital_id",                      is_granted: true,  granted_at: "2026-04-12T14:30:00Z", revoked_at: null },
  { id: "consent-003", tourist_id: "tourist-logged-in", consent_type: "medical_data_sharing",             is_granted: true,  granted_at: "2026-04-12T14:28:00Z", revoked_at: null },
  { id: "consent-004", tourist_id: "tourist-logged-in", consent_type: "emergency_contact_notification",   is_granted: true,  granted_at: "2026-04-12T14:27:00Z", revoked_at: null },
  { id: "consent-005", tourist_id: "tourist-logged-in", consent_type: "anomaly_detection",                is_granted: true,  granted_at: "2026-04-12T14:26:00Z", revoked_at: null },
  { id: "consent-006", tourist_id: "tourist-logged-in", consent_type: "analytics_data",                   is_granted: false, granted_at: null,                   revoked_at: null },
];

export const MOCK_CONSENT_LOG = [
  { type: "GPS Tracking",      action: "Enabled",                   time: "April 12, 2026 · 14:32 IST" },
  { type: "Digital ID",        action: "Issued on Polygon",         time: "April 12, 2026 · 14:30 IST" },
  { type: "Medical Data",      action: "Sharing Enabled",           time: "April 12, 2026 · 14:28 IST" },
  { type: "Emergency Contact", action: "Notification Enabled",      time: "April 12, 2026 · 14:27 IST" },
  { type: "Anomaly Detection", action: "Analysis Enabled",          time: "April 12, 2026 · 14:26 IST" },
  { type: "Account",           action: "Created — Onboarding",      time: "April 12, 2026 · 14:25 IST" },
];

export const MOCK_LOGGED_IN_TOURIST = {
  id: "tourist-logged-in",
  user_id: "uid-logged-in",
  full_name: "Vishal Lakshmikanthan",
  date_of_birth: "2006-09-15",
  nationality: "Indian",
  id_type: "aadhaar",
  phone_e164: "+919566383202",
  blood_type: "O+",
  medical_conditions: [],
  allergies: [],
  emergency_contact_name: "Lakshmikanthan R.",
  emergency_contact_phone: "+919566383202",
  emergency_contact_relation: "Father",
  preferred_language: "en",
  status: "safe",
  current_lat: 10.2381,
  current_lng: 77.4892,
  current_zone_id: "zone-001",
  current_zone_name: "Kodaikanal Lake & Boat Club Area",
  tracking_consent: true,
  did_issued: true,
  did_mock_id: "TSX-VL-20240112",
  did_mock_tx: "0xa3b9c2d8e4f15678901234abcdef5678901234abcdef5678901234abcdef5678",
  did_uri: "did:polygon:mumbai:0x7f4a2b8c9d3e1f56789012345678abcdef012345",
  did_ipfs_cid: "QmX4F7d2aPinataUploadMockHash456789abcdef012345678901234567890",
  did_block_number: 44211982,
  anomaly_score: 0.08,
  battery_pct: 74,
  last_seen: "28 sec ago",
  age: 19,
  email: "sec24cs046@sairamtap.edu.in",
};

export const MOCK_EMERGENCY_CONTACTS = {
  local: [
    { name: "Kodaikanal Police Station",    phone: "04542-241100", type: "Police",  distance_km: 1.4, response_min: 7  },
    { name: "Government Hospital Kodaikanal", phone: "04542-241212", type: "Medical", distance_km: 2.1, response_min: 12 },
    { name: "SDRF Unit — Palani",           phone: "04545-241600", type: "Rescue",  distance_km: 34,  response_min: 45 },
    { name: "Tamil Nadu Forest Department", phone: "04542-241099", type: "Forest",  distance_km: 1.8, response_min: 10 },
  ],
  national: [
    { name: "Emergency (Police / Fire / Medical)", phone: "112" },
    { name: "Tourist Helpline — Ministry of Tourism", phone: "1800-111-363" },
    { name: "Women's Helpline",            phone: "1091" },
    { name: "Ambulance",                   phone: "108" },
    { name: "Disaster Management (NDMA)",  phone: "1078" },
    { name: "NDRF National Control",       phone: "9711077372" },
    { name: "SDRF Tamil Nadu HQ",          phone: "0462-2350120" },
  ],
};

export const MOCK_NEARBY_PLACES = [
  { name: "Kodaikanal Lake", lat: 10.2381, lng: 77.4892, type: "safe",       distance: "You are here" },
  { name: "Coaker's Walk",   lat: 10.2291, lng: 77.4947, type: "warning",    distance: "0.8 km" },
  { name: "Bryant Park",     lat: 10.2347, lng: 77.4972, type: "safe",       distance: "0.5 km" },
  { name: "Pillar Rocks",    lat: 10.2194, lng: 77.4736, type: "warning",    distance: "1.1 km" },
  { name: "Guna Caves",      lat: 10.2167, lng: 77.4833, type: "danger",     distance: "1.4 km" },
  { name: "Berijam Lake",    lat: 10.1833, lng: 77.4167, type: "restricted", distance: "5.2 km" },
  { name: "Vattakanal",      lat: 10.2050, lng: 77.4650, type: "warning",    distance: "2.3 km" },
];

export const MOCK_ANALYTICS_SNAPSHOTS = [
  { date: "Apr 08", tourists: 38, alerts: 5, sos: 0, response_time: 12.4 },
  { date: "Apr 09", tourists: 41, alerts: 7, sos: 1, response_time: 9.1  },
  { date: "Apr 10", tourists: 29, alerts: 3, sos: 0, response_time: 14.8 },
  { date: "Apr 11", tourists: 52, alerts: 9, sos: 0, response_time: 7.5  },
  { date: "Apr 12", tourists: 44, alerts: 6, sos: 1, response_time: 8.9  },
  { date: "Apr 13", tourists: 48, alerts: 8, sos: 0, response_time: 6.3  },
  { date: "Apr 14", tourists: 47, alerts: 8, sos: 1, response_time: 7.2  },
];

// ─── INDIA-WIDE TOURIST PLACES (for full map view) ────────────────────────────

export const INDIA_TOURIST_PLACES = [
  // Tamil Nadu
  { name: "Kodaikanal",          lat: 10.2381, lng: 77.4892, state: "Tamil Nadu",         category: "hill_station", tourists_active: 47  },
  { name: "Ooty",                lat: 11.4102, lng: 76.6950, state: "Tamil Nadu",         category: "hill_station", tourists_active: 89  },
  { name: "Munnar",              lat: 10.0892, lng: 77.0595, state: "Kerala",             category: "hill_station", tourists_active: 71  },
  { name: "Rameswaram",          lat: 9.2882,  lng: 79.3175, state: "Tamil Nadu",         category: "pilgrimage",   tourists_active: 234 },
  { name: "Mahabalipuram",       lat: 12.6208, lng: 80.1927, state: "Tamil Nadu",         category: "heritage",     tourists_active: 112 },
  { name: "Meenakshi Temple",    lat: 9.9195,  lng: 78.1193, state: "Tamil Nadu",         category: "pilgrimage",   tourists_active: 311 },
  { name: "Palani",              lat: 10.4515, lng: 77.5191, state: "Tamil Nadu",         category: "pilgrimage",   tourists_active: 156 },
  { name: "Courtallam",          lat: 8.9347,  lng: 77.2742, state: "Tamil Nadu",         category: "waterfall",    tourists_active: 43  },
  { name: "Yercaud",             lat: 11.7745, lng: 78.2001, state: "Tamil Nadu",         category: "hill_station", tourists_active: 38  },
  { name: "Kanyakumari",         lat: 8.0883,  lng: 77.5385, state: "Tamil Nadu",         category: "coastal",      tourists_active: 198 },
  // Kerala
  { name: "Alleppey Backwaters", lat: 9.4981,  lng: 76.3388, state: "Kerala",             category: "nature",       tourists_active: 87  },
  { name: "Thekkady",            lat: 9.6000,  lng: 77.1667, state: "Kerala",             category: "wildlife",     tourists_active: 64  },
  { name: "Fort Kochi",          lat: 9.9658,  lng: 76.2421, state: "Kerala",             category: "heritage",     tourists_active: 119 },
  // North India
  { name: "Taj Mahal, Agra",     lat: 27.1751, lng: 78.0421, state: "Uttar Pradesh",      category: "heritage",     tourists_active: 412 },
  { name: "Varanasi Ghats",      lat: 25.3176, lng: 83.0104, state: "Uttar Pradesh",      category: "pilgrimage",   tourists_active: 198 },
  { name: "Jaipur Amber Fort",   lat: 26.9855, lng: 75.8513, state: "Rajasthan",          category: "heritage",     tourists_active: 231 },
  { name: "Jodhpur Blue City",   lat: 26.2389, lng: 73.0243, state: "Rajasthan",          category: "heritage",     tourists_active: 143 },
  { name: "Rishikesh",           lat: 30.1290, lng: 78.3214, state: "Uttarakhand",        category: "adventure",    tourists_active: 127 },
  { name: "Manali",              lat: 32.2396, lng: 77.1887, state: "Himachal Pradesh",   category: "hill_station", tourists_active: 88  },
  { name: "Leh",                 lat: 34.1526, lng: 77.5771, state: "Ladakh",             category: "adventure",    tourists_active: 53  },
  { name: "Shimla",              lat: 31.1048, lng: 77.1734, state: "Himachal Pradesh",   category: "hill_station", tourists_active: 76  },
  { name: "Kedarnath",           lat: 30.7346, lng: 79.0669, state: "Uttarakhand",        category: "pilgrimage",   tourists_active: 28  },
  { name: "Haridwar",            lat: 29.9457, lng: 78.1642, state: "Uttarakhand",        category: "pilgrimage",   tourists_active: 167 },
  // Northeast
  { name: "Kaziranga NP",        lat: 26.5775, lng: 93.1700, state: "Assam",              category: "wildlife",     tourists_active: 45  },
  { name: "Tawang Monastery",    lat: 27.5860, lng: 91.8670, state: "Arunachal Pradesh",  category: "pilgrimage",   tourists_active: 29  },
  { name: "Shillong",            lat: 25.5788, lng: 91.8933, state: "Meghalaya",          category: "hill_station", tourists_active: 58  },
  // West India
  { name: "Goa Beaches",         lat: 15.2993, lng: 74.1240, state: "Goa",               category: "coastal",      tourists_active: 324 },
  { name: "Ajanta Caves",        lat: 20.5519, lng: 75.7033, state: "Maharashtra",       category: "heritage",     tourists_active: 89  },
  { name: "Rann of Kutch",       lat: 23.7337, lng: 69.8597, state: "Gujarat",           category: "nature",       tourists_active: 56  },
  { name: "Somnath Temple",      lat: 20.8880, lng: 70.4013, state: "Gujarat",           category: "pilgrimage",   tourists_active: 134 },
  // South India
  { name: "Hampi Ruins",         lat: 15.3350, lng: 76.4600, state: "Karnataka",         category: "heritage",     tourists_active: 91  },
  { name: "Coorg",               lat: 12.3375, lng: 75.8069, state: "Karnataka",         category: "hill_station", tourists_active: 67  },
  { name: "Mysore Palace",       lat: 12.3052, lng: 76.6552, state: "Karnataka",         category: "heritage",     tourists_active: 188 },
  { name: "Puri Jagannath",      lat: 19.8045, lng: 85.8187, state: "Odisha",            category: "pilgrimage",   tourists_active: 178 },
];

export const MOCK_VERIFICATION_LOG = [
  { tourist_name: "Arun Kumar",   did_uri: "did:polygon:mumbai:0x7f4a...c82d", verified_at: "Today 08:32", result: "Approved", officer: "Kumar R." },
  { tourist_name: "Vishal Lakshmikanthan", did_uri: "did:polygon:mumbai:0x1b2c...d3e4", verified_at: "Today 09:15", result: "Approved", officer: "Kumar R." },
  { tourist_name: "Klaus Müller", did_uri: "did:polygon:mumbai:0x9f8e...7d6c", verified_at: "Today 09:28", result: "Approved", officer: "Kumar R." },
];

export const MOCK_ACTIVITY_FEED = [
  { type: "sos",      icon: "🆘", text: "SOS triggered — Vishal Lakshmikanthan",           sub: "09:39 · Coaker's Walk · Dispatching", color: "#C53030" },
  { type: "anomaly",  icon: "⚠",  text: "Anomaly alert — Raj Patel (0.71)",       sub: "09:30 · Guna Caves approach",         color: "#B45309" },
  { type: "anomaly",  icon: "⚠",  text: "Anomaly alert — Klaus Müller (0.78)",    sub: "09:28 · Guna Caves danger zone",      color: "#B45309" },
  { type: "geofence", icon: "📍", text: "Geofence breach — Meena Das",            sub: "09:15 · Berijam Lake boundary",       color: "#1A3C6E" },
  { type: "resolve",  icon: "✓",  text: "Alert resolved — Arjun Nair inactivity", sub: "08:55 · Checked in via phone",        color: "#046A38" },
  { type: "did",      icon: "🔐", text: "DID verified — Arun Kumar",              sub: "08:32 · Authority scan · Approved",   color: "#0D7680" },
  { type: "geofence", icon: "📍", text: "Geofence false positive — Chen Wei",     sub: "08:15 · Pillar Rocks GPS drift",      color: "#718096" },
  { type: "battery",  icon: "🔋", text: "Low battery — Vikram Singh (38%)",       sub: "08:10 · Vattakanal · Heart condition", color: "#B45309" },
];
